services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban_board_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - gem_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: bash -c "bundle install && bin/dev"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "3035:3035"
    environment:
      REDIS_URL: redis://redis:6379/0
      BINDING: 0.0.0.0
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
     CHOKIDAR_USEPOLLING: "true"
     CHOKIDAR_INTERVAL: "1000"  
    stdin_open: true
    tty: true
    command: bash -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

volumes:
  gem_cache:
  node_modules:
  db_data:
  redis_data: